# Generated by Django 4.2.7 on 2025-07-25 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('total_users', models.IntegerField(default=0, verbose_name='إجمالي المستخدمين')),
                ('new_users_today', models.IntegerField(default=0, verbose_name='مستخدمين جدد اليوم')),
                ('active_users_today', models.IntegerField(default=0, verbose_name='مستخدمين نشطين اليوم')),
                ('verified_users', models.IntegerField(default=0, verbose_name='مستخدمين موثقين')),
                ('total_items', models.IntegerField(default=0, verbose_name='إجمالي المنتجات')),
                ('new_items_today', models.IntegerField(default=0, verbose_name='منتجات جديدة اليوم')),
                ('available_items', models.IntegerField(default=0, verbose_name='منتجات متاحة')),
                ('sold_items', models.IntegerField(default=0, verbose_name='منتجات مباعة')),
                ('total_orders', models.IntegerField(default=0, verbose_name='إجمالي الطلبات')),
                ('new_orders_today', models.IntegerField(default=0, verbose_name='طلبات جديدة اليوم')),
                ('completed_orders', models.IntegerField(default=0, verbose_name='طلبات مكتملة')),
                ('pending_orders', models.IntegerField(default=0, verbose_name='طلبات معلقة')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الإيرادات')),
                ('revenue_today', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إيرادات اليوم')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='متوسط قيمة الطلب')),
                ('total_conversations', models.IntegerField(default=0, verbose_name='إجمالي المحادثات')),
                ('new_conversations_today', models.IntegerField(default=0, verbose_name='محادثات جديدة اليوم')),
                ('total_messages', models.IntegerField(default=0, verbose_name='إجمالي الرسائل')),
                ('ai_analyses_today', models.IntegerField(default=0, verbose_name='تحليلات ذكية اليوم')),
                ('ai_success_rate', models.FloatField(default=0, verbose_name='معدل نجاح الذكاء الاصطناعي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إحصائيات لوحة التحكم',
                'verbose_name_plural': 'إحصائيات لوحة التحكم',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث'), ('delete', 'حذف'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('view', 'عرض'), ('export', 'تصدير'), ('import', 'استيراد')], max_length=20, verbose_name='نوع العملية')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='نوع المحتوى')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='معرف الكائن')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المدير')),
            ],
            options={
                'verbose_name': 'نشاط المدير',
                'verbose_name_plural': 'أنشطة المديرين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'تصحيح'), ('INFO', 'معلومات'), ('WARNING', 'تحذير'), ('ERROR', 'خطأ'), ('CRITICAL', 'حرج')], max_length=10, verbose_name='المستوى')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('module', models.CharField(max_length=100, verbose_name='الوحدة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل النظام',
                'verbose_name_plural': 'سجلات النظام',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='dashboard_s_level_e7fe0d_idx'), models.Index(fields=['module'], name='dashboard_s_module_1ef590_idx'), models.Index(fields=['user'], name='dashboard_s_user_id_4a60f0_idx')],
            },
        ),
    ]
