# Generated by Django 4.2.7 on 2025-07-25 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='رقم الهاتف')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('user_type', models.CharField(choices=[('individual', 'فرد'), ('business', 'مؤسسة'), ('recycling_center', 'مركز إعادة تدوير')], default='individual', max_length=20, verbose_name='نوع المستخدم')),
                ('token', models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز التحقق')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='الصورة الشخصية')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='نبذة شخصية')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='الموقع')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المؤسسة')),
                ('business_license', models.CharField(blank=True, max_length=100, verbose_name='رقم الترخيص')),
                ('business_address', models.TextField(blank=True, verbose_name='عنوان المؤسسة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, verbose_name='موظف')),
                ('is_verified', models.BooleanField(default=False, verbose_name='موثق')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخر دخول')),
                ('total_items_posted', models.IntegerField(default=0, verbose_name='إجمالي المنتجات المنشورة')),
                ('total_orders_made', models.IntegerField(default=0, verbose_name='إجمالي الطلبات المقدمة')),
                ('rating_average', models.FloatField(default=0.0, verbose_name='متوسط التقييم')),
                ('rating_count', models.IntegerField(default=0, verbose_name='عدد التقييمات')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=10, verbose_name='اللغة المفضلة')),
                ('dark_mode', models.BooleanField(default=False, verbose_name='الوضع المظلم')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='إشعارات البريد الإلكتروني')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='الإشعارات المباشرة')),
                ('show_email', models.BooleanField(default=False, verbose_name='إظهار البريد الإلكتروني')),
                ('show_phone', models.BooleanField(default=False, verbose_name='إظهار رقم الهاتف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المقيم')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL, verbose_name='المقيم')),
            ],
            options={
                'verbose_name': 'تقييم المستخدم',
                'verbose_name_plural': 'تقييمات المستخدمين',
                'unique_together': {('rater', 'rated_user')},
            },
        ),
    ]
