# Generated by Django 4.2.7 on 2025-07-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_forgot_password',
            field=models.BooleanField(default=False, verbose_name='نسيت كلمة المرور'),
        ),
    ]
