# Generated by Django 4.2.7 on 2025-07-25 20:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='اللون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='items.category')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('is_negotiable', models.BooleanField(default=True, verbose_name='قابل للتفاوض')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='الصورة')),
                ('condition', models.CharField(choices=[('new', 'جديد'), ('like_new', 'شبه جديد'), ('good', 'جيد'), ('fair', 'مقبول'), ('poor', 'سيء')], default='good', max_length=20, verbose_name='الحالة')),
                ('weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الوزن (كيلو)')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='الأبعاد')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='المادة')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='خط العرض')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='خط الطول')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('pending', 'معلق'), ('sold', 'تم البيع'), ('expired', 'منتهي الصلاحية')], default='available', max_length=20, verbose_name='الحالة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='عاجل')),
                ('ai_analyzed', models.BooleanField(default=False, verbose_name='تم تحليله بالذكاء الاصطناعي')),
                ('ai_category_suggestion', models.CharField(blank=True, max_length=100, verbose_name='اقتراح الفئة بالذكاء الاصطناعي')),
                ('ai_condition_assessment', models.CharField(blank=True, max_length=20, verbose_name='تقييم الحالة بالذكاء الاصطناعي')),
                ('ai_price_suggestion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='اقتراح السعر بالذكاء الاصطناعي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('views_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('likes_count', models.IntegerField(default=0, verbose_name='عدد الإعجابات')),
                ('rating_average', models.FloatField(default=0.0, verbose_name='متوسط التقييم')),
                ('rating_count', models.IntegerField(default=0, verbose_name='عدد التقييمات')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.category', verbose_name='الفئة')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='items.item', verbose_name='المنتج')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مشاهدة المنتج',
                'verbose_name_plural': 'مشاهدات المنتجات',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/', verbose_name='الصورة')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='النص البديل')),
                ('is_primary', models.BooleanField(default=False, verbose_name='الصورة الرئيسية')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.item')),
            ],
            options={
                'verbose_name': 'صورة المنتج',
                'verbose_name_plural': 'صور المنتجات',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='items.item', verbose_name='المنتج')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_ratings', to=settings.AUTH_USER_MODEL, verbose_name='المقيم')),
            ],
            options={
                'verbose_name': 'تقييم المنتج',
                'verbose_name_plural': 'تقييمات المنتجات',
                'unique_together': {('item', 'rater')},
            },
        ),
        migrations.CreateModel(
            name='ItemLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='items.item', verbose_name='المنتج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_items', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعجاب بالمنتج',
                'verbose_name_plural': 'إعجابات المنتجات',
                'unique_together': {('item', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status', 'category'], name='items_item_status_6ca42c_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_at'], name='items_item_created_3cdd06_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['price'], name='items_item_price_cb7806_idx'),
        ),
    ]
