# Generated by Django 4.2.7 on 2025-07-25 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('inappropriate_item', 'منتج غير مناسب'), ('fake_item', 'منتج وهمي'), ('abusive_user', 'مستخدم مسيء'), ('spam', 'رسائل مزعجة'), ('fraud', 'احتيال'), ('inappropriate_content', 'محتوى غير مناسب'), ('copyright', 'انتهاك حقوق الطبع'), ('other', 'أخرى')], max_length=30, verbose_name='نوع البلاغ')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان البلاغ')),
                ('description', models.TextField(verbose_name='وصف البلاغ')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('under_review', 'تحت المراجعة'), ('resolved', 'تم الحل'), ('rejected', 'مرفوض'), ('escalated', 'تم التصعيد')], default='pending', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='reports/evidence/', verbose_name='صورة الدليل')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='reports/files/', verbose_name='ملف الدليل')),
                ('admin_response', models.TextField(blank=True, verbose_name='رد الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='المبلغ')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
            ],
            options={
                'verbose_name': 'بلاغ',
                'verbose_name_plural': 'البلاغات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('warning_sent', 'تم إرسال تحذير'), ('content_removed', 'تم حذف المحتوى'), ('user_suspended', 'تم إيقاف المستخدم'), ('user_banned', 'تم حظر المستخدم'), ('item_hidden', 'تم إخفاء المنتج'), ('no_action', 'لا يوجد إجراء')], max_length=20, verbose_name='نوع الإجراء')),
                ('description', models.TextField(verbose_name='وصف الإجراء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='reports.report', verbose_name='البلاغ')),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تم الإجراء بواسطة')),
            ],
            options={
                'verbose_name': 'إجراء البلاغ',
                'verbose_name_plural': 'إجراءات البلاغات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'priority'], name='reports_rep_status_047d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='reports_rep_report__dbb097_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx'),
        ),
    ]
