# Generated by Django 4.2.7 on 2025-07-25 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='معرف الجلسة')),
                ('session_type', models.CharField(choices=[('general', 'عام'), ('item_help', 'مساعدة في المنتج'), ('recycling_guide', 'دليل إعادة التدوير'), ('price_inquiry', 'استفسار عن السعر'), ('technical_support', 'دعم فني')], default='general', max_length=20, verbose_name='نوع الجلسة')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات السياق')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخر نشاط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة البوت الذكي',
                'verbose_name_plural': 'جلسات البوت الذكي',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ChatBotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'مستخدم'), ('bot', 'بوت'), ('system', 'نظام')], max_length=10, verbose_name='نوع الرسالة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='وقت المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_services.chatbot', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'رسالة البوت الذكي',
                'verbose_name_plural': 'رسائل البوت الذكي',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم النموذج')),
                ('model_type', models.CharField(choices=[('image_classification', 'تصنيف الصور'), ('text_classification', 'تصنيف النصوص'), ('price_prediction', 'توقع الأسعار'), ('content_moderation', 'مراجعة المحتوى'), ('chatbot', 'البوت الذكي')], max_length=30, verbose_name='نوع النموذج')),
                ('version', models.CharField(max_length=20, verbose_name='الإصدار')),
                ('config', models.JSONField(default=dict, verbose_name='الإعدادات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='الدقة')),
                ('avg_processing_time', models.FloatField(blank=True, null=True, verbose_name='متوسط وقت المعالجة')),
                ('total_requests', models.IntegerField(default=0, verbose_name='إجمالي الطلبات')),
                ('successful_requests', models.IntegerField(default=0, verbose_name='الطلبات الناجحة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='آخر استخدام')),
            ],
            options={
                'verbose_name': 'نموذج ذكي',
                'verbose_name_plural': 'النماذج الذكية',
                'unique_together': {('model_type', 'is_default')},
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('image_classification', 'تصنيف الصور'), ('text_analysis', 'تحليل النصوص'), ('price_suggestion', 'اقتراح السعر'), ('category_suggestion', 'اقتراح الفئة'), ('condition_assessment', 'تقييم الحالة'), ('content_moderation', 'مراجعة المحتوى')], max_length=30, verbose_name='نوع التحليل')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('input_text', models.TextField(blank=True, verbose_name='النص المدخل')),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='ai/input/', verbose_name='الصورة المدخلة')),
                ('input_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='نتائج التحليل')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='درجة الثقة')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='وقت المعالجة (ثانية)')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('related_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='items.item', verbose_name='المنتج المرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تحليل ذكي',
                'verbose_name_plural': 'التحليلات الذكية',
                'ordering': ['-created_at'],
            },
        ),
    ]
