# Generated by Django 4.2.7 on 2025-07-25 21:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_alter_item_image_alter_item_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('payment_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع'), ('refunded', 'مسترد')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('delivery_address', models.TextField(verbose_name='عنوان التسليم')),
                ('delivery_phone', models.CharField(max_length=15, verbose_name='رقم هاتف التسليم')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='ملاحظات التسليم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('expected_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم المتوقع')),
                ('buyer_notes', models.TextField(blank=True, verbose_name='ملاحظات المشتري')),
                ('seller_notes', models.TextField(blank=True, verbose_name='ملاحظات البائع')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_buyer', to=settings.AUTH_USER_MODEL, verbose_name='المشتري')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='items.item', verbose_name='المنتج')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_seller', to=settings.AUTH_USER_MODEL, verbose_name='البائع')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order_placed', 'تم تقديم الطلب'), ('order_accepted', 'تم قبول الطلب'), ('preparing', 'جاري التحضير'), ('ready_for_pickup', 'جاهز للاستلام'), ('in_transit', 'في الطريق'), ('delivered', 'تم التسليم')], max_length=20, verbose_name='الحالة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تم إنشاؤه بواسطة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'تتبع الطلب',
                'verbose_name_plural': 'تتبع الطلبات',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.order', verbose_name='الطلب')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة الطلب',
                'verbose_name_plural': 'رسائل الطلبات',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('buyer_to_seller', 'من المشتري للبائع'), ('seller_to_buyer', 'من البائع للمشتري')], max_length=20, verbose_name='نوع التقييم')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='orders.order', verbose_name='الطلب')),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_ratings_received', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المقيم')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='المقيم')),
            ],
            options={
                'verbose_name': 'تقييم الطلب',
                'verbose_name_plural': 'تقييمات الطلبات',
                'unique_together': {('order', 'rater', 'rating_type')},
            },
        ),
    ]
