# Generated by Django 4.2.7 on 2025-07-24 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_message', 'رسالة جديدة'), ('new_order', 'طلب جديد'), ('order_accepted', 'تم قبول الطلب'), ('order_rejected', 'تم رفض الطلب'), ('order_completed', 'تم إكمال الطلب'), ('order_cancelled', 'تم إلغاء الطلب'), ('item_liked', 'إعجاب بالمنتج'), ('item_rated', 'تقييم المنتج'), ('user_rated', 'تقييم المستخدم'), ('item_expired', 'انتهاء صلاحية المنتج'), ('system', 'إشعار نظام'), ('promotion', 'عرض ترويجي')], max_length=20, unique=True, verbose_name='نوع الإشعار')),
                ('title_ar', models.CharField(max_length=200, verbose_name='العنوان بالعربية')),
                ('title_en', models.CharField(max_length=200, verbose_name='العنوان بالإنجليزية')),
                ('message_ar', models.TextField(verbose_name='الرسالة بالعربية')),
                ('message_en', models.TextField(verbose_name='الرسالة بالإنجليزية')),
                ('email_subject_ar', models.CharField(blank=True, max_length=200, verbose_name='موضوع البريد الإلكتروني بالعربية')),
                ('email_subject_en', models.CharField(blank=True, max_length=200, verbose_name='موضوع البريد الإلكتروني بالإنجليزية')),
                ('email_body_ar', models.TextField(blank=True, verbose_name='محتوى البريد الإلكتروني بالعربية')),
                ('email_body_en', models.TextField(blank=True, verbose_name='محتوى البريد الإلكتروني بالإنجليزية')),
                ('sms_message_ar', models.CharField(blank=True, max_length=160, verbose_name='رسالة SMS بالعربية')),
                ('sms_message_en', models.CharField(blank=True, max_length=160, verbose_name='رسالة SMS بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'عالي'), ('urgent', 'عاجل')], default='normal', max_length=10, verbose_name='الأولوية الافتراضية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قالب الإشعار',
                'verbose_name_plural': 'قوالب الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_message', models.BooleanField(default=True, verbose_name='رسالة جديدة - بريد إلكتروني')),
                ('email_new_order', models.BooleanField(default=True, verbose_name='طلب جديد - بريد إلكتروني')),
                ('email_order_updates', models.BooleanField(default=True, verbose_name='تحديثات الطلب - بريد إلكتروني')),
                ('email_item_interactions', models.BooleanField(default=False, verbose_name='تفاعلات المنتج - بريد إلكتروني')),
                ('email_system_notifications', models.BooleanField(default=True, verbose_name='إشعارات النظام - بريد إلكتروني')),
                ('email_promotions', models.BooleanField(default=False, verbose_name='العروض الترويجية - بريد إلكتروني')),
                ('push_new_message', models.BooleanField(default=True, verbose_name='رسالة جديدة - إشعار فوري')),
                ('push_new_order', models.BooleanField(default=True, verbose_name='طلب جديد - إشعار فوري')),
                ('push_order_updates', models.BooleanField(default=True, verbose_name='تحديثات الطلب - إشعار فوري')),
                ('push_item_interactions', models.BooleanField(default=True, verbose_name='تفاعلات المنتج - إشعار فوري')),
                ('push_system_notifications', models.BooleanField(default=True, verbose_name='إشعارات النظام - إشعار فوري')),
                ('push_promotions', models.BooleanField(default=False, verbose_name='العروض الترويجية - إشعار فوري')),
                ('sms_new_order', models.BooleanField(default=False, verbose_name='طلب جديد - رسالة نصية')),
                ('sms_order_updates', models.BooleanField(default=False, verbose_name='تحديثات الطلب - رسالة نصية')),
                ('sms_system_notifications', models.BooleanField(default=False, verbose_name='إشعارات النظام - رسالة نصية')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='بداية الساعات الهادئة')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='نهاية الساعات الهادئة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعدادات الإشعارات',
                'verbose_name_plural': 'إعدادات الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_message', 'رسالة جديدة'), ('new_order', 'طلب جديد'), ('order_accepted', 'تم قبول الطلب'), ('order_rejected', 'تم رفض الطلب'), ('order_completed', 'تم إكمال الطلب'), ('order_cancelled', 'تم إلغاء الطلب'), ('item_liked', 'إعجاب بالمنتج'), ('item_rated', 'تقييم المنتج'), ('user_rated', 'تقييم المستخدم'), ('item_expired', 'انتهاء صلاحية المنتج'), ('system', 'إشعار نظام'), ('promotion', 'عرض ترويجي')], max_length=20, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'عالي'), ('urgent', 'عاجل')], default='normal', max_length=10, verbose_name='الأولوية')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True, verbose_name='رابط الإجراء')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
